<?php
/**
 * Desc  ：Animate.php   系统背景主题
 * Author: Cool-T 😀
 * Since : V1.0
 * Date  : 2018/10/30
 */

namespace app\admin\controller;


use think\facade\Request;
use app\admin\model\BgAnimate;

class Animate extends Base
{
    private $model;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new BgAnimate();
    }

    /**
     * 列表
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function index()
    {
        $list = BgAnimate::getList();
        $this->assign( 'list', $list );

        return $this->fetch();
    }

    /**
     * 添加
     * @return array|bool|mixed|\think\response\Json
     */
    public function add()
    {
        if( Request::isAjax() ){

            //验证数据
            $errMsg = $this->validateData( 'Animate', $_POST );
            if( $errMsg ) return $errMsg;

            $status = $this->model->save( $_POST );
            $this->endAction( $status, '添加站点背景主题' );

        }else{
            return $this->fetch();
        }
    }

    /**
     * 修改
     * @return array|bool|mixed|\think\response\Json
     */
    public function edit()
    {
        $id = input( 'id' );
        if( Request::isAjax() ){

            //验证
            $errMsg = $this->validateData( 'Animate', $_POST );
            if( $errMsg ) return $errMsg;

            //修改
            $status = $this->model->save( $_POST, [ 'id' => $id ] );
            $this->endAction( $status, '修改站点背景主题' );

        }else{
            $data = $this->model->get( $id );
            if( !$data ) abort( 404, '参数错误' );

            $this->assign( 'data', $data );
            return $this->fetch();
        }
    }

    /**
     * 删除
     */
    public function del()
    {
        $id = input( 'id' );

        if( !Request::isAjax() || !$id ) abort( 404, '页面不存在' );

        $count = \app\admin\model\Admin::whereInCount( 'theme_id', $id );

        if( $count > 0 ){
            $this->endAction( false, false, '要删除的主题下有' . $count . '个用户在使用，暂无法删除' );
        }

        //删除
        $status = BgAnimate::destroy( $id );
        $this->endAction( $status, '删除站点背景主题' );
    }


    /**
     * 状态修改
     */
    public function setField()
    {
        if( !Request::isAjax() ) abort( 404, '页面不存在' );

        //接收参数
        $field = input('field' );
        $value = input( 'value' );
        $id = input( 'id' );

        //修改
        $status = BgAnimate::whereInSetField( 'id', $id, $field, $value );
        $this->endAction( $status, '设置背景主题状态' );
    }

}