<?php
/**
 * Desc  ：system.php    系统全局配置
 * Author: Cool-T 😀
 * Since : V1.0
 * Date  : 2018/10/24
 */

namespace app\admin\controller;


use app\common\model\SystemConfig;
use think\db\Where;
use think\facade\Request;

class System  extends Base
{
    private $model;

    /**
     * 初始化
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new SystemConfig();
    }

    /**
     * 列表
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function index()
    {
        //where
        $where = new Where();
        if( isset( $_GET['key'] ) && $_GET['key'] ) $where['key'] = [ 'like', "%{$_GET['key']}%" ];

        //查询
        $list = SystemConfig::getList( $where, [ 'id' => 'desc' ] );

        $this->assign( 'list', $list );
        return $this->fetch();
    }

    /**
     * 添加
     * @return mixed|\think\response\Json
     */
    public function add()
    {
        if( Request::isAjax() ){

            if( isset( $_POST['imgs'] ) ){
                $_POST['value'] = implode(',',$_POST['imgs']);
            }

            //验证
            $errMsg = $this->validateData( 'System', $_POST );
            if( $errMsg ) return $errMsg;

            //添加
            $status = $this->model->save( $_POST );
            $this->endAction( $status, '添加系统全局配置' );

        }else{
            return $this->fetch();
        }
    }

    /**
     * 修改数据
     * @return array|bool|mixed
     */
    public function edit()
    {
        $id  = input( 'id' );
        if( Request::isAjax() ){

            if( isset( $_POST['imgs'] ) ){
                $_POST['value'] = implode(',',$_POST['imgs']);
            }

            //验证
            $errMsg = $this->validateData( 'System', $_POST );
            if( $errMsg ) return $errMsg;


            //修改数据
            $status = $this->model->save( $_POST, [ 'id' => $id ] );
            $this->endAction( $status, '修改系统全局配置' );

        }else{
            $data = $this->model->get( $id );
            if( !$data ) abort( 404, '参数错误' );

            $this->assign( 'data', $data );
            return $this->fetch();
        }
    }

    /**
     * 删除数据
     */
    public function del()
    {
        $id = input( 'id' );
        if( !Request::isAjax() || !$id ) abort( 404, '页面不存在' );

        $status = SystemConfig::destroy( $id );
        $this->endAction( $status, '删除系统全局配置' );
    }

}